# Generated by Django 5.0.6 on 2024-05-22 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_leave_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='message',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
