# Generated by Django 5.0.6 on 2024-05-22 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_leave_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='dept',
            name='dept_image',
            field=models.ImageField(blank=True, null=True, upload_to='dept_image/'),
        ),
    ]
