# Generated by Django 5.0.6 on 2024-05-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_dept_dept_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(blank=True, max_length=25, null=True)),
                ('trainer', models.CharField(blank=True, max_length=25, null=True)),
                ('trainerid', models.IntegerField(blank=True, null=True)),
                ('trainee', models.CharField(blank=True, max_length=25, null=True)),
                ('traineeid', models.IntegerField(blank=True, null=True)),
                ('batchname', models.CharField(blank=True, max_length=25, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
