# Generated by Django 5.0.6 on 2024-05-23 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_batch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='trainee',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='trainer',
        ),
    ]
