# Generated by Django 5.0.6 on 2024-05-23 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_batch_trainee_remove_batch_trainer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='traineeid',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
