# Generated by Django 5.0.6 on 2024-05-23 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_batch_traineeid'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='trainer',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
