# Generated by Django 5.0.6 on 2024-05-25 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_batch_trainer'),
    ]

    operations = [
        migrations.CreateModel(
            name='notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('managerid', models.IntegerField(blank=True, null=True)),
                ('message', models.CharField(blank=True, max_length=250, null=True)),
                ('traineeid', models.IntegerField(blank=True, null=True)),
                ('trainerid', models.IntegerField(blank=True, null=True)),
                ('batchname', models.CharField(blank=True, max_length=250, null=True)),
                ('dept', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
