# Generated by Django 5.0.6 on 2024-05-27 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
