# Generated by Django 5.0.6 on 2024-05-29 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_batch_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='managerid',
            new_name='trainerid',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='managername',
        ),
    ]
