# Generated by Django 5.0.6 on 2024-05-30 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_rename_managerid_notification_trainerid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectname', models.CharField(blank=True, max_length=250, null=True)),
                ('batchname', models.CharField(blank=True, max_length=250, null=True)),
                ('traineeid', models.IntegerField(blank=True, null=True)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('status', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='projectsubmit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectname', models.CharField(blank=True, max_length=250, null=True)),
                ('projectid', models.IntegerField(blank=True, null=True)),
                ('batchname', models.CharField(blank=True, max_length=250, null=True)),
                ('traineeid', models.IntegerField(blank=True, null=True)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('status', models.CharField(blank=True, max_length=250, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='project_image/')),
            ],
        ),
    ]
