# Generated by Django 5.0.6 on 2024-05-30 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_project_projectsubmit'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='batchid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
