# Generated by Django 5.0.6 on 2024-05-30 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_project_batchid'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='trainerid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='trainername',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
