# Generated by Django 5.0.6 on 2024-05-30 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_project_trainerid_project_trainername'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='batchid',
        ),
    ]
