# Generated by Django 5.0.6 on 2024-05-30 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_project_image_alter_projectsubmit_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='traineename',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
