# Generated by Django 5.0.6 on 2024-05-30 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_project_traineename'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='traineeimage',
            field=models.ImageField(blank=True, null=True, upload_to='trainee_image/'),
        ),
    ]
